In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
from numpy import nan as NA

In [9]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [13]:
cleaned = data.dropna()

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4]=NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.randn(7, 3))

In [20]:
df.iloc[:4, 1] = NA

In [21]:
df.iloc[:2, 2] = NA

In [22]:
df

0         1         2
0  0.837129       NaN       NaN
1 -0.039905       NaN       NaN
2 -0.156978       NaN -0.381588
3 -0.789047       NaN  0.174036
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [23]:
df.dropna()

0         1         2
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [24]:
df.dropna(thresh=2)

0         1         2
2 -0.156978       NaN -0.381588
3 -0.789047       NaN  0.174036
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [25]:
df.fillna(0)

0         1         2
0  0.837129  0.000000  0.000000
1 -0.039905  0.000000  0.000000
2 -0.156978  0.000000 -0.381588
3 -0.789047  0.000000  0.174036
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [26]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.837129  0.500000  0.000000
1 -0.039905  0.500000  0.000000
2 -0.156978  0.500000 -0.381588
3 -0.789047  0.500000  0.174036
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [27]:
df.fillna(0, inplace=True)

In [28]:
df

0         1         2
0  0.837129  0.000000  0.000000
1 -0.039905  0.000000  0.000000
2 -0.156978  0.000000 -0.381588
3 -0.789047  0.000000  0.174036
4  0.260060 -0.235688 -0.197363
5  0.487283  0.683531  0.191357
6  0.311992 -0.278880 -0.804417

In [29]:
df = pd.DataFrame(np.random.randn(6, 3))

In [30]:
df.iloc[2:, 1] = NA

In [31]:
df.iloc[4:, 2] = NA

In [32]:
df

0         1         2
0  0.063226  1.562575  0.164007
1 -0.746831  0.337747 -1.099623
2  0.247570       NaN -0.479278
3 -0.314682       NaN -0.233704
4 -0.657824       NaN       NaN
5 -0.435660       NaN       NaN

In [33]:
df.fillna(method='ffill')

0         1         2
0  0.063226  1.562575  0.164007
1 -0.746831  0.337747 -1.099623
2  0.247570  0.337747 -0.479278
3 -0.314682  0.337747 -0.233704
4 -0.657824  0.337747 -0.233704
5 -0.435660  0.337747 -0.233704

In [34]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.063226  1.562575  0.164007
1 -0.746831  0.337747 -1.099623
2  0.247570  0.337747 -0.479278
3 -0.314682  0.337747 -0.233704
4 -0.657824       NaN -0.233704
5 -0.435660       NaN -0.233704

In [35]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [36]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [37]:
#Przekształcanie danych

In [38]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data['v1'] = range(7)

In [43]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [46]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [48]:
lowercased = data['food'].str.lower()

In [49]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [50]:
data['animal'] = lowercased.map(meat_to_animal)

In [51]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [58]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index = ['Ohio', 'Colorado', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])

In [61]:
transform = lambda x: x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [65]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [66]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [67]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [68]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [69]:
#Dyskretyzacja i podział na koszyki

In [70]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [71]:
bins = [18 , 25, 35, 60, 100]

In [72]:
cats = pd.cut(ages, bins)

In [73]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [74]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [75]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [76]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [77]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [78]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [79]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [80]:
data = np.random.rand(20)

In [81]:
pd.cut(data, 4, precision=2)

[(0.3, 0.51], (0.51, 0.73], (0.3, 0.51], (0.73, 0.94], (0.3, 0.51], ..., (0.51, 0.73], (0.51, 0.73], (0.081, 0.3], (0.081, 0.3], (0.73, 0.94]]
Length: 20
Categories (4, interval[float64]): [(0.081, 0.3] < (0.3, 0.51] < (0.51, 0.73] < (0.73, 0.94]]

In [82]:
data = np.random.randn(1000)

In [83]:
cats = pd.qcut(data, 4)

In [84]:
cats

[(-3.304, -0.734], (-0.00356, 0.644], (-3.304, -0.734], (0.644, 3.152], (-0.00356, 0.644], ..., (-3.304, -0.734], (-0.734, -0.00356], (0.644, 3.152], (-0.00356, 0.644], (-0.00356, 0.644]]
Length: 1000
Categories (4, interval[float64]): [(-3.304, -0.734] < (-0.734, -0.00356] < (-0.00356, 0.644] < (0.644, 3.152]]

In [85]:
pd.value_counts(cats)

(0.644, 3.152]        250
(-0.00356, 0.644]     250
(-0.734, -0.00356]    250
(-3.304, -0.734]      250
dtype: int64

In [86]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.335, -0.00356], (-0.00356, 1.226], (-3.304, -1.335], (-0.00356, 1.226], (-0.00356, 1.226], ..., (-1.335, -0.00356], (-1.335, -0.00356], (-0.00356, 1.226], (-0.00356, 1.226], (-0.00356, 1.226]]
Length: 1000
Categories (4, interval[float64]): [(-3.304, -1.335] < (-1.335, -0.00356] < (-0.00356, 1.226] < (1.226, 3.152]]

In [87]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018148     0.011162    -0.039466     0.027612
std       0.981824     1.068196     0.993827     1.047816
min      -2.805548    -3.477573    -3.197622    -3.497169
25%      -0.649602    -0.683340    -0.726461    -0.641616
50%       0.071281     0.004414    -0.053828     0.071556
75%       0.684981     0.729146     0.648109     0.717103
max       3.485111     3.726021     3.552854     2.837929

In [88]:
col = data[2]
col[np.abs(col)>3]

196   -3.197622
910   -3.005120
975    3.552854
Name: 2, dtype: float64

In [89]:
data[(np.abs(data > 3). any(1))]

0         1         2         3
38   3.485111 -0.575581  0.975995 -1.007024
106 -0.362336  3.178171 -1.256802 -2.062435
512 -0.782252  3.726021 -0.339594 -0.712576
767  1.147884  3.106918 -0.822501 -0.773993
975  1.736633 -0.352297  3.552854 -0.594460

In [90]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [91]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017663     0.010629    -0.039816     0.028366
std       0.980227     1.063633     0.991354     1.045482
min      -2.805548    -3.000000    -3.000000    -3.000000
25%      -0.649602    -0.683340    -0.726461    -0.641616
50%       0.071281     0.004414    -0.053828     0.071556
75%       0.684981     0.729146     0.648109     0.717103
max       3.000000     3.000000     3.000000     2.837929

In [92]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0  1.0 -1.0 -1.0
3  1.0 -1.0 -1.0  1.0
4  1.0 -1.0 -1.0 -1.0

In [93]:
#permutacje i próbkowanie losowe

In [94]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [95]:
sampler = np.random.permutation(5)

In [96]:
sampler

array([4, 0, 1, 3, 2])

In [97]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [98]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

In [99]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

In [100]:
choices = pd.Series([5, 7, -1, 6, 4])

In [101]:
draws = choices.sample(n=10, replace=True)

In [102]:
draws

1    7
1    7
1    7
1    7
2   -1
2   -1
2   -1
4    4
3    6
4    4
dtype: int64

In [103]:
#przetwarzanie wskaźników i zmiennych zastępczych

In [104]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 
                   'data1': range(6)})

In [105]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [106]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [107]:
df_with_dummy = df[['data1']].join(dummies)

In [108]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [109]:
mnames = ['movie_id', 'title', 'genres']

In [128]:
movies = pd.read_table('dane/movielens/movies.dat', sep='::',engine='python',header=None, names=mnames)

In [129]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [130]:
all_genres = []

In [131]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [132]:
genres = pd.unique(all_genres)

In [133]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [134]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [135]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [136]:
gen = movies.genres[0]

In [137]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [138]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [139]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [140]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [141]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [142]:
np.random.seed(12345)

In [143]:
values = np.random.rand(10)

In [144]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [145]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [146]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [147]:
val = 'a, b, guido'

In [148]:
val.split(',')

['a', ' b', ' guido']

In [149]:
pieces = [x.strip() for x in val.split(',')]

In [150]:
pieces

['a', 'b', 'guido']

In [151]:
first, second, third = pieces

In [152]:
first + '::' + second + '::' + third

'a::b::guido'

In [153]:
'::'.join(pieces)

'a::b::guido'

In [154]:
'guido' in val

True

In [155]:
val.index(',')

1

In [156]:
val.find(':')

-1

In [157]:
val.index(':')

ValueError: substring not found

In [158]:
val.count(',')

2

In [159]:
val.replace(',', '::')

'a:: b:: guido'

In [160]:
import re

In [161]:
text = "foo bar\tbaz  \tqux"

In [162]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [163]:
regex = re.compile('\s+')

In [164]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [165]:
regex.findall(text)

[' ', '\t', '  \t']

In [166]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [167]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [168]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [169]:
m = regex.search(text)

In [170]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [171]:
text[m.start():m.end()]

'dave@google.com'

In [172]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [173]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [175]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [176]:
m = regex.match('wesm@bright.net')

In [177]:
m.groups()

()

In [178]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [179]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [180]:
data = pd.Series(data)

In [181]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [182]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [183]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object